### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Abeautifulsnow** [GoToUse/ggit#2]
- [x] 判断本地已有git文件夹，直接退出
- [x] 优化gitclone.com的clone逻辑，根据其接口判断repo是否已被gitclone.com收录，如果没有退出该mirror
  - [ ]  后续可以使得不存在gitclone的项目，实现接口添加至gitclone中，方便日后直接从gitclone中下载。
  - [ ] 待定
- [x] 支持增加clone时其他git参数，比如--depth
- [ ] 实现指定git文件或者release下载，可以用`https://www.jsdelivr.com/`作为cdn代理，拼接git文件链接快速下载
- [x] #9
- [ ] 美化输出，寻找解决方案
- [x] 增加cobra命令支持, 丰富功能
- [x] #11
- [ ] 支持set_timeout，超时自动退出该host [待考虑]

**Comment by Abeautifulsnow** [comment]
```go
func checkIsAGitRepo(folderName string) bool {
	gitP := lookGitPath()
	rootP := "/Users/dapeng/Documents/code/git"
	testP := path.Join(rootP, folderName)
	os.Chdir(testP)
	err := RunCommand(gitP, []string{"rev-parse", "--is-inside-work-tree"}...)

	return err == nil
}
```

**Comment by Abeautifulsnow** [comment]
```go
func main() {
	queryPath := "https://www.gitclone.com/gogs/search/clonesearch?q=ggit"
	res, err := http.Get(queryPath)
	if err != nil {
		panic(err)
	}
	defer res.Body.Close()
	if res.StatusCode != 200 {
		log.Fatalf("status code error: %d %s", res.StatusCode, res.Status)
	}
	doc, err := goquery.NewDocumentFromReader(res.Body)
	if err != nil {
		panic(err)
	}
	// 未搜索到repo
	noResult := doc.Find("p.clonesearch-noresult")
	if noResult.Length() != 0 {
		fmt.Println("gitclone did't have this repo. Maybe you can add your git-repo to gitclone.com manually. Details see website: https://gitclone.com/")
		return
	}
	doc.Find("div.item").Each(func(i int, s *goquery.Selection) {
		title := s.Find("a.name").Text()
		// 去除空字符串情况
		if len(title) != 0 {
			trimTitle := strings.TrimSpace(title)
			fmt.Println(trimTitle)
		}
	})
}
```
